# Tensor 연산

In [1]:
import tensorflow as tf

아래의 기본 연산은 특수 메서드를 이용하여 연산자 오버로딩이 되어 있으므로 그냥 연산자 기호를 사용하는게 가능!

* `tf.add`: 덧셈
* `tf.subtract`: 뺄셈
* `tf.multiply`: 곱셈
* `tf.divide`: 나눗셈
* `tf.pow`: n-제곱
* `tf.negative`: 음수 부호


In [2]:
a = tf.range(6, dtype=tf.int32)
b = 2 * tf.ones(6, dtype=tf.int32)

tf.add(a, b)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7], dtype=int32)>

In [3]:
a + b

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7], dtype=int32)>

**여러가지 연산**

* `tf.abs`: 절대값
* `tf.sign`: 부호
* `tf.round`: 반올림
* `tf.ceil`: 올림
* `tf.floor`: 내림
* `tf.square`: 제곱
* `tf.sqrt`: 제곱근
* `tf.maximum`: 두 텐서의 각 원소에서 최댓값만 반환.
* `tf.minimum`: 두 텐서의 각 원소에서 최솟값만 반환.
* `tf.cumsum`: 누적합
* `tf.cumprod`: 누적곱


In [4]:
tf.maximum(a, b)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5], dtype=int32)>

#### Axis 이해하기

In [5]:
rank_2 = tf.random.normal((3, 3))

In [6]:
rank_2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.03136346, -0.80681604,  0.19710521],
       [ 0.9664774 , -0.7884808 , -0.6580173 ],
       [-0.79263896, -1.1426497 ,  1.1991194 ]], dtype=float32)>

In [7]:
rank_2[0]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 0.03136346, -0.80681604,  0.19710521], dtype=float32)>

In [8]:
rank_2[0, 0]

<tf.Tensor: shape=(), dtype=float32, numpy=0.03136346>

In [9]:
rank_3 = tf.random.normal((3, 3, 3))

In [10]:
rank_3

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[-0.27332327, -0.29570046, -0.2768901 ],
        [ 2.289374  , -1.4415187 , -0.7046093 ],
        [ 1.9637772 ,  0.5766597 , -1.0870825 ]],

       [[-0.30871943,  1.6242074 , -0.56803346],
        [ 1.338942  ,  0.16558863, -1.9459119 ],
        [ 0.19500704,  0.3411417 ,  0.4522926 ]],

       [[ 0.03696585, -0.7880044 , -0.66169226],
        [-0.743536  ,  0.99831676, -1.3999386 ],
        [-0.851995  , -0.11317895, -0.3043217 ]]], dtype=float32)>

In [11]:
rank_4 = tf.random.normal((3, 3, 3, 3))

In [12]:
rank_4

<tf.Tensor: shape=(3, 3, 3, 3), dtype=float32, numpy=
array([[[[-0.9094843 , -1.034508  , -1.3004289 ],
         [-1.7539141 , -0.232938  ,  0.12617634],
         [-0.38601002,  0.69840974,  0.01375935]],

        [[ 0.1840541 ,  0.7283121 , -0.181765  ],
         [ 0.25419262, -1.0991135 ,  1.1651949 ],
         [-0.09891643,  0.23026213,  1.2013762 ]],

        [[-3.4220855 ,  0.99202853,  1.8695016 ],
         [-0.6135304 , -0.3340123 ,  0.8727263 ],
         [ 0.2245716 ,  0.12712295, -0.698049  ]]],


       [[[-0.02593638, -0.8616296 , -1.0686133 ],
         [-0.9329005 , -0.44818887,  1.7689141 ],
         [ 0.93001306,  0.01030262,  0.704607  ]],

        [[ 0.2888123 , -0.0512911 ,  0.31852433],
         [-0.08366559,  0.26390845,  0.23467241],
         [-0.8115626 , -1.4978572 ,  0.5692983 ]],

        [[ 0.3562928 ,  1.2289641 , -0.18591376],
         [ 0.5861924 ,  0.2374711 , -1.5998375 ],
         [ 0.15923774, -0.03146991,  0.15096964]]],


       [[[-1.3205129 ,  0.3827

In [13]:
rank_4[1,0,0,2]

<tf.Tensor: shape=(), dtype=float32, numpy=-1.0686133>

**차원 축소 연산**

* `tf.reduce_mean`: 설정한 축의 평균을 구한다.
* `tf.reduce_max`: 설정한 축의 최댓값을 구한다.
* `tf.reduce_min`: 설정한 축의 최솟값을 구한다.
* `tf.reduce_prod`: 설정한 축의 요소를 모두 곱한 값을 구한다.
* `tf.reduce_sum`: 설정한 축의 요소를 모두 더한 값을 구한다.

In [14]:
a

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5], dtype=int32)>

In [ ]:
tf.reduce_sum(a, axis=0),

(<tf.Tensor: shape=(), dtype=int32, numpy=15>,)

In [15]:
tf.reduce_sum(a, axis=0, keepdims=True),

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([15], dtype=int32)>,)

In [16]:
b = tf.random.normal(((2,7)))
b

<tf.Tensor: shape=(2, 7), dtype=float32, numpy=
array([[-0.8909374 , -1.0296777 , -0.4370198 ,  1.2866362 ,  1.6367208 ,
        -0.19578207, -1.1975374 ],
       [-0.37514788,  1.0672107 ,  1.2432306 ,  0.7920304 , -0.24542458,
         0.57577497, -1.222402  ]], dtype=float32)>

In [18]:
tf.reduce_mean(b, axis=0)

<tf.Tensor: shape=(7,), dtype=float32, numpy=
array([-0.63304263,  0.01876646,  0.40310538,  1.0393333 ,  0.6956481 ,
        0.18999645, -1.2099698 ], dtype=float32)>

In [19]:
tf.reduce_mean(b, axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.11822821,  0.26218173], dtype=float32)>

In [23]:
c = tf.random.normal(((4,3,2)))
c

<tf.Tensor: shape=(4, 3, 2), dtype=float32, numpy=
array([[[-1.4439391 ,  1.43478   ],
        [-0.40267417, -0.8865361 ],
        [ 0.5919033 , -0.16411342]],

       [[ 0.20529386,  0.6946342 ],
        [-0.4838849 ,  0.26178002],
        [-0.1867889 , -0.516961  ]],

       [[ 0.56147254, -0.7324238 ],
        [ 0.9019852 , -0.2844219 ],
        [ 2.2929747 ,  1.8368094 ]],

       [[-0.38310438,  0.9853673 ],
        [-1.9115652 , -1.1130351 ],
        [ 1.293921  , -1.3552474 ]]], dtype=float32)>

In [24]:
tf.reduce_mean(c, axis=0)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.26506925,  0.5955894 ],
       [-0.47403476, -0.50555325],
       [ 0.9980025 , -0.04987809]], dtype=float32)>

In [25]:
tf.reduce_mean(c, axis=1)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-0.41823664,  0.12804349],
       [-0.15512665,  0.14648442],
       [ 1.2521442 ,  0.27332124],
       [-0.33358288, -0.49430504]], dtype=float32)>

In [26]:
tf.reduce_mean(c, axis=2)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-0.00457954, -0.64460516,  0.21389496],
       [ 0.44996405, -0.11105244, -0.35187495],
       [-0.08547562,  0.30878168,  2.064892  ],
       [ 0.30113146, -1.5123001 , -0.03066319]], dtype=float32)>

행렬과 관련된 연산

* `tf.matmul`: 내적
* `tf.linalg.inv`: 역행렬


In [20]:
a = tf.constant([[2, 0], [0, 1]], dtype=tf.float32)
b = tf.constant([[1, 1], [1, 1]], dtype=tf.float32)
tf.matmul(a, b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [1., 1.]], dtype=float32)>

In [21]:
a,b

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[2., 0.],
        [0., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>)

In [28]:
a = tf.constant([[2, 0], [0, 1]], dtype=tf.float32)
tf.linalg.inv(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.5, 0. ],
       [0. , 1. ]], dtype=float32)>

**크기 및 차원을 바꾸는 명령**
 (잘 사용됩니다!!)

이를 사용 할 때는 축을 잘 이해하고 사용하시면 좋습니다.

* `tf.reshape`: 벡터 행렬의 크기 변환
* `tf.transpose`: 전치 연산
* `tf.expand_dims`: 지정한 축으로 차원을 추가
* `tf.squeeze`: 벡터로 차원을 축소

In [27]:
a = tf.range(6, dtype=tf.int32)      # [0, 1, 2, 3, 4, 5]
print("a     :", a, "\n")
a_2d = tf.reshape(a, (2, 3))  # 1차원 벡터는 2x3 크기의 2차원 행렬로 변환
print("a_2d  :", a_2d, "\n")
a_2d_t = tf.transpose(a_2d)   # 2x3 크기의 2차원 행렬을 3x2 크기의 2차원 행렬로 변환
print("a_2d_t:", a_2d_t, "\n")
a_3d = tf.expand_dims(a_2d, 0) # 2x3 크기의 2차원 행렬을 1x2x3 크기의 3차원 행렬로 변환
print("a_3d  :", a_3d, "\n")
a_4d = tf.expand_dims(a_3d, 3) # 1x2x3 크기의 3차원 행렬을 1x2x3x1 크기의 4차원 행렬로 변환
print("a_4d  :", a_4d, "\n")
a_1d = tf.squeeze(a_4d)
print("a_1d  :", a_1d, "\n")   # 1x2x3x1 크기의 4차원 행렬을 1차원 벡터로 변환

a     : tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int32) 

a_2d  : tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32) 

a_2d_t: tf.Tensor(
[[0 3]
 [1 4]
 [2 5]], shape=(3, 2), dtype=int32) 

a_3d  : tf.Tensor(
[[[0 1 2]
  [3 4 5]]], shape=(1, 2, 3), dtype=int32) 

a_4d  : tf.Tensor(
[[[[0]
   [1]
   [2]]

  [[3]
   [4]
   [5]]]], shape=(1, 2, 3, 1), dtype=int32) 

a_1d  : tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32) 



**텐서를 나누거나 두 개 이상의 텐서를 합치는 명령**

* `tf.slice`: 특정 부분을 추출
* `tf.split`: 분할
* `tf.concat`: 합치기
* `tf.tile`: 복제-붙이기
* `tf.stack`: 합성
* `tf.unstack`: 분리

In [29]:
a = tf.reshape(tf.range(12), (3, 4))
a

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [30]:
tf.slice(a, [0, 1], [2, 3])   # (0, 1)위치에서 (2개, 3개)만큼 뽑아낸다.

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [5, 6, 7]], dtype=int32)>

In [31]:
a1, a2 = tf.split(a, num_or_size_splits=2, axis=1)  # 가로축(axis=1)을 따라 2개로 분할
print(a1)
print(a2)

tf.Tensor(
[[0 1]
 [4 5]
 [8 9]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  3]
 [ 6  7]
 [10 11]], shape=(3, 2), dtype=int32)


In [32]:
tf.concat([a1, a2], 1) # 가로축(axis=1)을 따라 a1, a2를 합치기

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [33]:
tf.tile(a1, [1, 3])  # 가로축(axis=1)을 따라 3개로 복사-붙이기

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[0, 1, 0, 1, 0, 1],
       [4, 5, 4, 5, 4, 5],
       [8, 9, 8, 9, 8, 9]], dtype=int32)>

In [34]:
a3 = tf.stack([a1, a2])  # 3x2 행렬 a1, a2를 추가적인 차원으로 붙여서 2x3x2 고차원 텐서 생성
a3

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]]], dtype=int32)>

In [35]:
tf.unstack(a3, axis=1)  # 2x3x2 고차원 텐서를 0차원으로 풀어서 3개의 2x2 행렬 생성

[<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[0, 1],
        [2, 3]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[4, 5],
        [6, 7]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 8,  9],
        [10, 11]], dtype=int32)>]

#### 간단 퀴즈

다음 코드를 에러 없이 실행하라.

In [42]:
a = tf.constant(((1, 2, 3), (1, 2, 3)))
b = tf.constant([1, 2, 3])

tf.matmul(a, b)

InvalidArgumentError: ignored

In [ ]:
tf.matmul()